name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - run: rustup component add clippy

      - name: Lint
        run: cargo clippy -- -D warnings

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - run: rustup component add rustfmt

      - name: fmt
        run: cargo fmt --all -- --check

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - run: mkdir /tmp/shiro-wallet

      - run: bash test-mocks/start_services.sh  

      - name: Run tarpaulin
        env:
          RUST_TEST_THREADS: 1
          BITCOIN_NETWORK_NAME: regtest
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --release --out Xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
